CREATE TABLE DEVICE (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    BRAND VARCHAR(50),
    STATE VARCHAR(10),
    CREATIONTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT CHECK_STATE CHECK (STATE IN ('available', 'in-use', 'inactive'))
);

INSERT INTO DEVICE(ID, NAME, BRAND, STATE, CREATIONTIME) VALUES (1, 'DEVICE1', 'BRAND1', 'available', CURRENT_TIMESTAMP);